version: "3.6"
services:
 nginx-distribution:
        image: myopenresty
        container_name: nginx-distribution
        working_dir: /usr/local/openresty
        ports:
          - "8001:80"
        stdin_open: true
        networks:
          cache-network:
             ipv4_address: 192.168.1.8
        tty: true
        privileged: true
        volumes:
            - /Users/mac/code/openresty/project/conf/nginx/distribute:/usr/local/openresty/nginx/conf
            - /Users/mac/code/openresty/project/code/nginx/distribute:/usr/local/openresty/lualib/project
 nginx-application:
        image: myopenresty
        container_name: nginx-application
        working_dir: /usr/local/openresty
        ports:
          - "8002:80"
        stdin_open: true
        networks:
            cache-network:
             ipv4_address: 192.168.1.9
        tty: true
        privileged: true
        volumes:
              - /Users/mac/code/openresty/project/conf/nginx/application:/usr/local/openresty/nginx/conf
              - /Users/mac/code/openresty/project/code/nginx/application:/usr/local/openresty/lualib/project
 nginx-application-1:
          image: myopenresty
          container_name: nginx-application-1
          working_dir: /nginx-test
          ports:
            - "8003:80"
          stdin_open: true
          networks:
             cache-network:
               ipv4_address: 192.168.1.10
          tty: true
          privileged: true
          volumes:
              - /Users/mac/code/openresty/project/conf/nginx/application:/usr/local/openresty/nginx/conf
              - /Users/mac/code/openresty/project/code/nginx/application:/usr/local/openresty/lualib/project
networks:
    cache-network:
      external:
         name: redis-network